kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coresvc-pvc
  namespace: loadstar-coresvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-zrs
  resources:
    requests:
      storage: 2Gi